#!/usr/bin/env bash
# Write a Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

echo $$ > /var/run/myscript.pid

trap 'echo Y U no love me?!' SIGINT
trap "rm -r /var/run/myscript.pid" SIGQUIT SIGTERM
trap 'pkill -f  10-process_and_pid_file' SIGTERM SIGTERM

while true
do
        echo "To infinity and beyond"
	trap 'echo I hate the kill command' SIGTERM
done
