#!/usr/bin/env bash
# Write a Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

pgrep -f 10-process_and_pid_file > /var/run/myscript.pid

while true
do
	echo To infinity and beyond
	trap 'echo I hate the kill command' SIGTERM
	trap 'echo Y U no love me?!' SIGINT
done
trap 'rm  /var/run/myscript.pid' SIGQUIT || SIGTERM
trap 'pkill -f  10-process_and_pid_file' SIGQUIT || SIGTERM
