#!/usr/bin/env bash
# Write a Bash script that displays a list of currently running processes.
# shellcheck disable=SC2009
# Requirements:
# - Must show all processes, for all users, including those which might not have a TTY
# - Display in a user-oriented format
# - Show process hierarchy

ps -faux | grep 'bash' 
